#!/usr/bin/env bash

gcc -O2 -s -Wall -march=native -mtune=native -fomit-frame-pointer -Wl,--as-needed \
-o lsct \
-DNDEBUG -DRELEASE \
-std=c99 \
lsct.c	\
-ffunction-sections -fdata-sections -Wl,--gc-sections	\
-lmagic
